### ISSUE TITLE
How can I remove this driver after installing it?

### ISSUE THREAD

**Issue by rez1-inf** [nlkguy/archer-t2u-plus-linux#1]
Hi, i have successfully installed this driver in Raspberry Pi 4 running Ubuntu 20.10 64-bit.
But I don't have the wifi adapter, since I decided to go for a later model, (Archer T3U plus).
So i was wondering if i should to prevent any conflict, delete this driver for T2U plus before I install anything else.

Thank you guys... u made the steps very easy to follow..

**Comment by MaxALEau** [comment]
https://github.com/nlkguy/archer-t2u-plus-linux#uninstall-driver-in-linux
