### ISSUE TITLE
Resolution of Ubuntu changed for some reason

### ISSUE THREAD

**Issue by ShubhadipBH** [nlkguy/archer-t2u-plus-linux#3]
Hey, new ubuntu 20.4 user here!
So, Installed the Dirver but immedietly after the resolution changed and stuck at 1024X768 & no other options are available.
Please tell me how to fix this.
Thanks.

**Comment by ShubhadipBH** [comment]
Update: It's fixed.
I had to reinstall the drivers using:
sudo ubuntu-drivers autoinstall
and reboot.

Thanks @nlkguy  for this driver. Saved my life!

**Comment by nlkguy** [comment]
sorry bro for not replying fast , didnt checked mail for last few days

**Comment by nlkguy** [comment]
if you cant go to the setings and chenge the resolution (sometimes the
"apply" button id hidden under)

there is a commandline option - already installed in ubuntu to manage
displays - its called "xrandr"
 just type

xrandr -s <resolution>
