### ISSUE TITLE
Running into an error after installing driver

### ISSUE THREAD

**Issue by DarumasLegs** [nlkguy/archer-t2u-plus-linux#4]
When I type: "sudo make dkms_install", I get this:
mkdir -p /usr/src/8812au-5.6.4.2_35491.20191025
cp -r * /usr/src/8812au-5.6.4.2_35491.20191025
dkms add -m 8812au -v 5.6.4.2_35491.20191025

Creating symlink /var/lib/dkms/8812au/5.6.4.2_35491.20191025/source ->
                 /usr/src/8812au-5.6.4.2_35491.20191025

DKMS: add completed.
dkms build -m 8812au -v 5.6.4.2_35491.20191025
Error! echo
Your kernel headers for kernel 5.10.17-v7+ cannot be found at
/lib/modules/5.10.17-v7+/build or /lib/modules/5.10.17-v7+/source.
make: *** [Makefile:2304: dkms_install] Error 1

Where can I find the correct kernel headers?

**Comment by MaxALEau** [comment]
Hello!
Do you have try `sudo apt update && sudo apt upgrade && sudo apt autoremove` ?

**Comment by BurnhamR** [comment]
Having the same issue.



> Hello! Do you have try `sudo apt update && sudo apt upgrade && sudo apt autoremove` ?

Sadly, this doesn't fix it

**Comment by avierywan** [comment]
Same issue

**Comment by PatrickParks12345** [comment]
I am having the same issue as well

**Comment by mapokapo** [comment]
I think you need to install the Linux kernel headers that correspond to the current Linux kernel version you have installed. Try running `sudo apt install linux-headers-$(uname -r)`.

If that doesn't work, then that means your current Linux kernel version doesn't have the kernel modules in the repository, meaning your kernel is compiled from a 3rd party source (most common on ARM devices like Android) or you need to update your sources in /etc/apt/sources.list.

In case of ARM devices with no support for kernel modules, you need to add the driver to the source kernel repo for your device, compile it, and then flash it to your device.
